<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $book                            = new Book();
        $book->name_book                 = "Sách nghệ thuật giao tiếp thành công";
        $book->created_at                = date("Y-m-d");
        $book->updated_at                =  date("Y-m-d");
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2016/03/nghe-thuat-giao-tiep-de-thanh-cong-214x300.jpg";
        $book->category_id               = "1";
        $book->price                      = "100000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Khéo ăn nói";
        $book->image_book                = "https://toplist.vn/images/800px/kheo-an-noi-se-co-duoc-thien-ha-174596.jpg";
        $book->category_id               = "1";
        $book->price                     = "150000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Khéo ăn nói";
        $book->image_book                = "https://toplist.vn/images/800px/kheo-an-noi-se-co-duoc-thien-ha-174596.jpg";
        $book->category_id               = "1";
        $book->price                     = "80000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Giao tiếp đỉnh cao";
        $book->image_book                = "https://cf.shopee.vn/file/5851478962b428589049e234f81d026c";
        $book->category_id               = "1";
        $book->price                     = "90000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Giao tiếp không chỉ bằng ngôn từ";
        $book->image_book                = "https://newshop.vn/public/uploads/content/jpg5e0486aeda51d.jpg";
        $book->category_id               = "1";
        $book->price                     = "100000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Những cuộc thám hiểm vĩ đại";
        $book->image_book                = "https://salt.tikicdn.com/cache/w1200/ts/product/ae/f8/3a/6c0529f382f06efbbd7d086efd92e6fa.jpg";
        $book->category_id               = "2";
        $book->price                     = "200000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách hai văn năm dưới đáy biển";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2016/01/Hai-van-dam-duoi-bien-Jules-Verne-211x300.jpg";
        $book->category_id               = "2";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách cuộc thám hiểm vào lòng đất";
        $book->image_book                = "https://readvii.com/wp-content/uploads/2020/04/sach-cuoc-tham-hiem-vao-long-dat-194x300.png";
        $book->category_id               = "2";
        $book->price                     = "120000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Thám hiểm vũ trụ";
        $book->image_book                = "https://vn-test-11.slatic.net/p/3d9786dd227beca43a760474552e0ea2.jpg_360x360q90.jpg_.webp";
        $book->category_id               = "2";
        $book->price                     = "140000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách chuyện Thám hiểm ";
        $book->image_book                = "https://www.nxbtre.com.vn/Images/Book/NXBTreStoryFull_29562011_035607.jpg";
        $book->category_id               = "2";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Đắc Nhân Tâm";
        $book->image_book                = "https://top10meohay.com/wp-content/uploads/2017/08/14-2.jpg";
        $book->category_id               = "3";
        $book->price                     = "140000";
        $book->price                     = "110000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Thay đổi tư duy";
        $book->image_book                = "https://sachnoi.com.vn/wp-content/uploads/2020/10/lam-chu-tu-duy-thay-doi-van-menh.jpg";
        $book->category_id               = "3";
        $book->price                     = "140000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Chuẩn Pháp Luân";
        $book->image_book                = "https://khaimo.com/wp-content/uploads/2017/12/4hqJQR-20170524-nhung-trai-nghiem-phep-mau-cua-nguoi-phu-nu-tu-mot-cuon-sach-co.jpg";
        $book->category_id               = "3";
        $book->price                     = "140000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách tôi tài và bạn cũng tài";
        $book->image_book                = "https://trenkesach.com/wp-content/uploads/2017/03/sach-ban-chay-nhat-cua-adam-khoo-toi-tai-gioi-ban-cung-the-1.jpg";
        $book->category_id               = "3";
        $book->price                     = "140000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách đời ngắn đừng ngủ dài";
        $book->image_book                = "https://cdn.chanhtuoi.com/uploads/2018/05/w400/nhung-cuon-sach-hay-6.jpg.webp";
        $book->category_id               = "3";
        $book->price                     = "140000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách dám nghĩ lớn";
        $book->image_book                = "https://muasachhay.vn/wp-content/uploads/2016/10/dam-nghi-lon-mua-sach-hay-690x1024.jpg";
        $book->category_id               = "4";
        $book->price                     = "130000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách dám nghĩ để thành công";
        $book->image_book                = "https://chiasemoi.com/wp-content/uploads/2018/03/nghi-lon-de-thanh-cong.jpg";
        $book->category_id               = "4";
        $book->price                     = "130000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách dám nghĩ lớn";
        $book->image_book                = "https://salt.tikicdn.com/cache/400x400/ts/product/d0/14/b9/ce9929fa0d5678c92ef804b1289624d9.jpg";
        $book->category_id               = "4";
        $book->price                     = "130000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách thương yêu bụt dạy";
        $book->image_book                = "https://salt.tikicdn.com/cache/400x400/ts/product/7d/c2/bd/b6f1844257e67ffcabcbcb59dd6d332d.jpg";
        $book->category_id               = "5";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách hạt giống thương yêu";
        $book->image_book                = "https://product.hstatic.net/1000186499/product/18_96706d5a336b4947b42ef1ccd2cc167e.jpg";
        $book->category_id               = "5";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách yêu thương và tự do";
        $book->image_book                = "https://timcachkiemtien.com/wp-content/uploads/2019/09/Y%C3%AAu-th%C6%B0%C6%A1ng-v%C3%A0-t%E1%BB%B1-do.jpg";
        $book->category_id               = "5";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Chang hoang dã";
        $book->image_book                = "https://media.dautuvietnam.com.vn/2021/06/10/9925/1623290608-changhoangdgu-1623146539750x0-1551.jpg";
        $book->category_id               = "6";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Chú chó đợi chờ";
        $book->image_book                = "https://gacsach.com/diendan/proxy.php?image=https%3A%2F%2Ffarm1.staticflickr.com%2F954%2F41970552911_8733f7c70e_b.jpg&hash=d4e2d29f112eda3d752df14b0208722a";
        $book->category_id               = "6";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách nanh trắng";
        $book->image_book                = "https://gacsach.com/diendan/proxy.php?image=https%3A%2F%2Ffarm1.staticflickr.com%2F947%2F40163496590_d0ae6529da.jpg&hash=7ef0f1420f230b81484bc65a37572ed2";
        $book->category_id               = "6";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Tiếng gọi nơi hoang dã";
        $book->image_book                = "https://gacsach.com/diendan/proxy.php?image=https%3A%2F%2Ffarm1.staticflickr.com%2F944%2F41970552661_29cd247375.jpg&hash=edaa8b91ac3c37f63eb68bd300732151";
        $book->category_id               = "6";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Tiếng gọi nơi hoang dã";
        $book->image_book                = "https://gacsach.com/diendan/proxy.php?image=https%3A%2F%2Ffarm1.staticflickr.com%2F832%2F41970553031_fa17d60b01.jpg&hash=526a4a74b2009104274adc6cd96de930";
        $book->category_id               = "6";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách nếu gặp người ấy ch tôi gửi lời chào";
        $book->image_book                = "http://www.elle.vn/wp-content/uploads/2018/02/08/Nh%E1%BB%AFng-cu%E1%BB%91n-s%C3%A1ch-hay-nh%E1%BA%A5t-vi%E1%BA%BFt-v%E1%BB%81-t%C3%ACnh-y%C3%AAu-3.jpg";
        $book->category_id               = "7";
        $book->price                     = "180000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách thăng hoa hay là bi kịch";
        $book->image_book                = "https://cf.shopee.vn/file/ec166fb25312addf7c7e24b5b4f319c2";
        $book->category_id               = "7";
        $book->price                     = "180000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách một người không còn là tất cả";
        $book->image_book                = "https://toplist.vn/images/800px/tinh-yeu-va-tuoi-tre-375379.jpg";
        $book->category_id               = "7";
        $book->price                     = "180000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách em chưa từng quên anh";
        $book->image_book                = "https://vtv1.mediacdn.vn/thumb_w/650/2017/emchuatung-1487732421158.jpg";
        $book->category_id               = "7";
        $book->price                     = "180000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách tình yêu đơn phương";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2018/03/sach-hay-ve-tinh-yeu-don-phuong.jpg";
        $book->category_id               = "7";
        $book->price                     = "180000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách nhà giả kim";
        $book->image_book                = "https://salt.tikicdn.com/ts/product/97/e5/fc/da05988cbbe45e27c84763929f19ea00.jpg";
        $book->category_id               = "8";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách hoàng tử bé";
        $book->image_book                = "https://toplist.vn/images/800px/hoang-tu-be-253625.jpg";
        $book->category_id               = "8";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Tuổi trẻ đáng giá bao nhiêu";
        $book->image_book                = "https://storage.googleapis.com/ops-shopee-files-live/live/shopee-blog/2019/07/tuoi-tre-dang-gia-bao-nhieu.jpg";
        $book->category_id               = "8";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách bình tĩnh khi ế mãnh mẽ khi yêu";
        $book->image_book                = "https://storage.googleapis.com/ops-shopee-files-live/live/shopee-blog/2019/07/binh-tinh-khi-e-manh-me-khi-yeu.png";
        $book->category_id               = "8";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Điều kỳ diệu của tiệm tạp hóa";
        $book->image_book                = "https://storage.googleapis.com/ops-shopee-files-live/live/shopee-blog/2019/07/dieu-ky-dieu-cua-tiem-tap-hoa-1.jpg";
        $book->category_id               = "8";
        $book->price                     = "160000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Những Nhân Vật Nổi Tiếng Thế Giới";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2017/06/Nhung-nhan-vat-noi-tieng-the-gioi-700x1024.jpg";
        $book->category_id               = "9";
        $book->price                     = "200000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Cuộc đời kỳ lạ của Nikola Tesla";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2019/10/sach-cuoc-doi-ky-la-cua-nikola.png";
        $book->category_id               = "9";
        $book->price                     = "200000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Maria Montessori Cuộc Đời";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2019/10/sach-maria-montessori-cuoc-doi-va-su-nghiep.png";
        $book->category_id               = "9";
        $book->price                     = "200000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Shinzo Abe Và Gia Tộc";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2019/10/sach-shinzo-abe-gia-toc-tuyet-dinh.png";
        $book->category_id               = "9";
        $book->price                     = "200000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Tiểu Sử Steve Jobs";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2015/10/tieu-su-steve-jobs.jpg";
        $book->category_id               = "9";
        $book->price                     = "200000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách hẹn ước vầng dưới trắng";
        $book->image_book                = "https://anh.eva.vn//upload/1-2014/images/2014-02-20/1392915336-hihi.jpg";
        $book->category_id               = "10";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Khi Lỗi Thuộc Về Những Vì Sao";
        $book->image_book                = "https://readvii.com/wp-content/uploads/2019/12/sach-khi-loi-thuoc-ve-nhung-vi-sao.png";
        $book->category_id               = "10";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Anna Karenina";
        $book->image_book                = "https://readvii.com/wp-content/uploads/2020/01/sach-anna-karenina.png";
        $book->category_id               = "10";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách trước ngày em đến";
        $book->image_book                = "https://readvii.com/wp-content/uploads/2019/12/sach-truoc-ngay-em-den.png";
        $book->category_id               = "10";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Vợ Người Du Hành Thời Gian";
        $book->image_book                = "https://readvii.com/wp-content/uploads/2019/12/sach-vo-nguoi-du-hanh-thoi-gian.png";
        $book->category_id               = "10";
        $book->price                     = "170000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách Trí tưởng tượng mở con đường";
        $book->image_book                = "https://cf.shopee.vn/file/56ef75478b60b456ceb6594974d338c1";
        $book->category_id               = "11";
        $book->price                     = "90000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách mở khóa trí tưởng tượng";
        $book->image_book                = "https://wiibook.net/wp-content/uploads/2021/06/sach-mo-khoa-tri-tuong-tuong-hon-250-cach-dap-tan-buon-chan-232x300.png";
        $book->category_id               = "11";
        $book->price                     = "90000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách người bạn tưởng tượng";
        $book->image_book                = "https://salt.tikicdn.com/ts/product/c9/28/32/1e196479bbd7dd78c96634877eedbb2d.jpg";
        $book->category_id               = "11";
        $book->price                     = "90000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách quá giang vào ngân hà";
        $book->image_book                = "https://downloadsach.com/wp-content/uploads/2017/12/bi_kip_qua_giang_vao_ngan_ha-198x300.jpg";
        $book->category_id               = "11";
        $book->price                     = "90000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "Sách trí tưởng tượng cho con";
        $book->image_book                = "https://wiibook.net/wp-content/uploads/2021/02/sach-bi-quyet-nuoi-duong-tri-tuong-tuong-cho-con-199x300.png";
        $book->category_id               = "11";
        $book->price                     = "120000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "sách hành trình về phương đông";
        $book->image_book                = "https://media-cdn.laodong.vn/storage/newsportal/Uploaded/DangThiChung/2015_09_18/vh_opt_NLZL.jpeg";
        $book->category_id               = "12";
        $book->price                     = "110000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "sách Trần Quốc Toản";
        $book->image_book                = "https://newshop.vn/public/uploads/products/12012/tieu-thuyet-lich-su-tran-quoc-toan.gif";
        $book->category_id               = "12";
        $book->price                     = "110000";
        $book->save();
        $book                            = new Book();
        $book->created_at                = date("Y-m-d");
        $book->updated_at                = date("Y-m-d");
        $book->name_book                 = "sách nam quốc sơn hà";
        $book->image_book                = "https://sachhuyenhoc.info/wp-content/uploads/2019/02/Nam-Qu%E1%BB%91c-S%C6%A1n-H%C3%A0-Tr%C6%B0%E1%BB%9Dng-Thi%C3%AAn-Ti%E1%BB%83u-Thuy%E1%BA%BFt-L%E1%BB%8Bch-S%E1%BB%AD.jpg";
        $book->category_id               = "12";
        $book->price                     = "110000";
        $book->save();
    }
}
